name: smarthealth
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  geolocator: ^9.0.2
  google_maps_flutter: ^2.3.1
  geocoding: ^2.1.0
  http: ^1.1.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  google_maps: ^6.3.0
  flutter_rating_bar: ^4.0.1
  flutter_calendar_week: ^3.0.0
  booking_calendar: ^1.1.9
  file_picker: ^5.5.0
  flutter_screenutil: ^5.8.4
  carousel_slider: ^4.2.1
  flutter_mobile_vision_2: ^0.1.15
  image_picker: ^1.0.2
  flutter_pdfview: ^1.3.1
  shared_preferences: ^2.2.0
  path_provider: any
  url_launcher: ^6.1.12
  permission_handler: ^10.4.3
  intl: any
  photo_view: ^0.14.0
  charts_flutter: ^0.12.0
  flutter_blue: ^0.8.0

  collection: ^1.15.0-nullsafety.5
  uuid: ^3.0.7
  fl_chart: ^0.62.0
  flutter_dialogs: ^2.0.1
  rename: ^2.1.1




#  camera: ^0.10.5+4

















dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/stethoscope.png
    - assets/doctor.png
    - assets/time.png
    - assets/location.png
    - assets/homee.png
    - assets/ph.png
    - assets/he.png
    - assets/hee.jpg
    - assets/path.jpg
    - assets/l.jpg
    - assets/h.png
    - assets/tt.png
    - assets/d.png
    - assets/a.png
    - assets/pr.png
    - assets/medi.png
    - assets/lab.png
    - assets/dig.png
    - assets/r.png
    - assets/help.png
    - assets/emer.png
    - assets/set.png
    - assets/amb.png
    - assets/mail.png
    - assets/image1.jpeg
    - assets/image2.jpeg
    - assets/image3.jpeg
    - assets/image4.jpeg
    - assets/b.jpg
    - assets/b.p.png
    - assets/google-plus.png
    - assets/twitter.png
    - assets/facebook.png
    - assets/logo.png
    - assets/k.png
    - assets/add-user.png
    - assets/nextt.png
    - assets/view.png
    - assets/archieve.png
    - assets/email.png
    - assets/delete.png
    - assets/cloud-upload.png
    - assets/scan.png
    - assets/upload.png
    - assets/plus.png
    - assets/pharmacy.jpg
    - assets/p.png
    - assets/profile.png
    - assets/cart.png
    - assets/motorcycle.png
    - assets/camera.png
    - assets/trash.png
    - assets/f.jpg
    - assets/supplies.png
    - assets/microscope.png
    - assets/empire.png
    - assets/hospital-bed.png
    - assets/google-maps.png
    - assets/empty.jpg



